
[workspace]
members = [
    "keygen",
    "keys",
    "proto", 
    "service"]
resolver = "2"

[workspace.dependencies]
# Common versions used across packages
tokio = { version = "1.36", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rand = "0.8"
thiserror = "1.0.49"
base64 = "0.21.5"
log = "0.4.17"
k256 = "0.13.2"
sha2 = "0.10.8"
futures = "0.3"
prost = "0.11"
tonic = "0.8"
keygen = { path = "keygen", version = "0.1.0" }
keys = { path = "keys", version = "0.1.0" }
proto = { path = "proto", version = "0.1.0"}
uuid = {version = "=1.8.0" , features = ["v4","fast-rng","macro-diagnostics", "serde"]}
 
