[package]
name = "utils"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive", "std"] }
serde_json = "1.0"
clap = { version = "4.0.14", features = ["derive"] }
log = "0.4.17"
