[package]
name = "node_key_gen"
version = "0.1.0"
edition = "2024"

[dependencies]
libp2p = { workspace = true }
async-trait = { workspace = true }
tokio = { workspace = true }
clap = { version = "4.5.28", features = ["derive"] }
serde_json = { workspace = true }
serde = { workspace = true }