[package]
name = "proto"
version = "0.1.0"
edition = "2024"

[dependencies]
prost = "0.11"
tonic = "0.8"
serde = { version = "1.0", features = ["derive"] }

[build-dependencies]
tonic-build = "0.8"
prost-build = "0.11.1"
